name: Multiple Jobs Contributing to Artifact

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        run: |
          mkdir artifacts
          echo "File from job1" > artifacts/job1_file.txt

      - run: echo "PATH=$GITHUB_WORKSPACE/artifacts/job1_file.txt" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: shared-artifact
          path: ${{ env.PATH }}
          if-no-files-found: error
