name: Artifact

on: [push, workflow_dispatch]

jobs:
  FileCreation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: python3 artifact.py
    - uses: actions/upload-artifact@v4
      with:
        name: OUTPUT
        path: /tmp/output

  DownloadFile:
    runs-on: ubuntu-latest
    needs:  [FileCreation]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: OUTPUT
        path: output/
    - run: cat output/file3.txt
