name: Testing

on:
  push:

jobs:
  First:
    strategy:
      matrix:
        ID: [1, 2, 3, 4, 5]
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir /tmp/test1
          mkdir /tmp/test2
          echo "test1_$id" > /tmp/test1/file$id.txt
          echo "test2_$id" > /tmp/test2/file$id.txt
        env:
          id: ${{ matrix.ID }}
      - uses: actions/upload-artifact@v4
        with:
          name: REPORT_${{ matrix.ID }}
          path: /tmp/**
          retention-days: 1

  Second:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: REPORT_*
          path: /tmp
          merge-mutiple: true
      - run: tree /tmp
  
          
