name: Testing

on: push

jobs:
  SET_ENV: 
    runs-on: ubuntu-latest
    outputs:
      OUTPUT: ${{ env.LIST }}
    steps:
      - run: |
          range() {
            local n=$1
            local result=$(for ((i=0; i<n; i++)); do echo -n "$i"; if ((i<n-1)); then echo -n ", "; fi; done; echo)
            echo "[$result]"
          }
          LIST=$(range 10)
          echo $LIST
  ENV:
    needs: SET_ENV
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ID: ${{ fromJson(needs.SET_ENV.outputs.OUTPUT) }}
        
    steps:
      - run: echo $ID
        env:
          ID: ${{ matrix.ID }}
