name: Testing

on: push

jobs:
  JOB1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ID: ${{ formJson(vars.JOBS }}
    steps:
      - run: echo $ID
        env: 
          ID : ${{ matrix.ID }}
          NUMBER_OF_JOBS: ${{ echo var.JOBS | jq -r '. | length' }}
