name: Testing

on: [workflow_dispatch, push]

jobs:
  JOB1:
    runs-on: ubuntu-latest
    outputs:
      OUTPUT: ${{ env.OUTPUT }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "OUTPUT=$(python3 main.py)" >> $GITHUB_ENV
  JOB2:
    runs-on: ubuntu-latest
    needs: JOB1
    strategy:
      matrix:
        KEY: ${{ fromJson(needs.JOB1.outputs.OUTPUT) }}

    steps:
      - uses: actions/checkout@v4
      - run: python3 test.py
        env:
          KEY: ${{ matrix.KEY }}
