name: Testing

on: [workflow_dispatch, push]

jobs:
  JOB1:
    runs-on: ubuntu-latest
    outputs:
      OUTPUT: ${{ env.OUTPUT }}
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t job1 -f Dockerfile_1 .
      - run: |
          echo "OUTPUT=$(docker run --rm job1)" >> $GITHUB_ENV
  JOB2:
    runs-on: ubuntu-latest
    needs: JOB1
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t job2 -f Dockerfile_2 .
      - run: docker run --rm --env-file <(env) job2
        env:
          KEY: ${{ toJson(fromJson(needs.JOB1.outputs.OUTPUT)) }}
