name: Testing

on: push

jobs:
  SET_ENV: 
    runs-on: ubuntu-latest
    outputs:
      OUTPUT: ${{ env.LIST }}
    steps:
      - run: |
          GenerateList() { result=$(for ((i=0; i<$1; i++)); do echo -n "$i"; if ((i<$1-1)); then echo -n ", "; fi; done; echo); return $result;}
          LIST=$(GenerateList 10)
          echo $LIST
  ENV:
    needs: SET_ENV
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ID: ${{ fromJson(needs.SET_ENV.outputs.OUTPUT) }}
        
    steps:
      - run: echo $ID
        env:
          ID: ${{ matrix.ID }}
