name: Testing

on: push

jobs:
  JOB1:
    env: 
      MATRIX: ${{ toJson([1, 2, 3]) }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ID: ${{ fromJson(env.MATRIX) }}
    steps:
      - run: echo $ID
        env: ${{ matrix.ID }}
