name: Testing

on: push

jobs:
  SET_ENV: 
    runs-on: ubuntu-latest
    outputs:
      OUTPUT: ${{ env.LIST }}
    steps:
      - run: |
          GenerateList() {
            result=$(for ((i=0; i<n; i++)); do echo -n "$i"; if ((i<n-1)); then echo -n ", "; fi; done; echo);
            return $result
          }
          echo "LIST=$(GenerateList 10)" >> $GITHUB_ENV
  ENV:
    needs: SET_ENV
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ID: ${{ fromJson(needs.SET_ENV.outputs.OUTPUT) }}
        
    steps:
      - run: echo $ID
        env:
          ID: ${{ matrix.ID }}
