name: Testing

on: [workflow_dispatch, push]

jobs:
  JOB1:
    runs-on: ubuntu-latest
    outputs:
      OUTPUT: ${{ env.OUTPUT }}
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t job1 -f Dockerfile_1 .
      - run: |
          echo "OUTPUT=$(docker run --rm job1)" >> $GITHUB_ENV
  JOB2:
    runs-on: ubuntu-latest
    needs: JOB1
    steps:
      - run: |
          VAR=$(echo $KEY | jq -r 'select(.first==1)')
          echo $VAR
        env: 
          KEY: ${{ needs.JOB1.outputs.OUTPUT }}
