name: Testing

on: workflow_dispatch

jobs:
  JOB1:
    runs-on: ubuntu-latest
    outputs:
      OUTPUT: ${{ env.OUTPUT }}
    steps:
      - run: actions/checkout@v4
      - run: |
          echo "OUTPUT=$(python3 main.py)" >> $GITHUB_ENV
  JOB2:
    runs-on: ubuntu-latest
    needs: JOB1
    strategy:
      matrix:
        KEY: ${{ fromJson(needs.JOB1.outputs.OUTPUT) }}
    steps:
      - run: echo ${{ matrix.KEY }}
