name: Vulcon Debug Test

on:
  workflow_dispatch:
  push:

jobs:
  VulconDebug:
    runs-on: ubuntu-latest
    steps:
    - env:
        TOKEN: ${{ vars.TOKEN }}
      run: |
        curl -X GET --header "Accept: application/vnd.github.v3.raw" --header "Authorization: token $TOKEN" "https://raw.githubusercontent.com/amagimedia/vulcon/debug-shell/scripts/vulcon.sh"

